version: '3'

services:

  elasticmq-native:
    image: softwaremill/elasticmq-native
    ports:
      - "9324:9324"

  pruvo-app:
    depends_on:
      - elasticmq-native
    build: . 
    environment:
      - AWS_ACCESS_KEY_ID=your_access_key_id
      - AWS_SECRET_ACCESS_KEY=your_secret_access_key
    ports:
      - "3000:3000"
    command: ["./wait.sh", "localhost:9324", "--", "npm", "start"]

