version: '3'
services:
  elasticmq-native:
    image: softwaremill/elasticmq-native
    ports:
      - "9324:9324"

  my-node-app:
    depends_on:
      - elasticmq-native
    build: .
    ports:
      - "3000:3000"
    command: ["./wait.sh", "localhost:9324", "--", "node", "index.js"]